# Generated by Django 2.2.9 on 2020-02-27 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200227_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='incorrect_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=3),
        ),
    ]
