# Generated by Django 2.2.9 on 2020-02-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200227_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_one',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='code_two',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
