# Generated by Django 2.2.9 on 2020-02-29 13:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200229_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='incorrect_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=3),
        ),
    ]
