# Generated by Django 2.2.9 on 2020-02-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20200227_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='looking_for_work',
            field=models.BooleanField(default=True),
        ),
    ]
