# Generated by Django 2.2.9 on 2020-02-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20200227_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
