# Generated by Django 2.2.9 on 2020-02-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
