# Generated by Django 2.2.9 on 2020-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20200227_1217'),
        ('jwt_auth', '0008_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='businesses',
            field=models.ManyToManyField(blank=True, related_name='user', to='businesses.Business'),
        ),
    ]
