# Generated by Django 2.2.9 on 2020-03-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0010_auto_20200302_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
